// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tvobaaqyhjjsvddwhrdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2b2JhYXF5aGpqc3ZkZHdocmRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NjMzMTksImV4cCI6MjA3MzUzOTMxOX0.sjQ1JCF_f_4LKkB_0WUkPYi50NdF_eavU7i9O4x8USw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});